[package]
name = "collectr"
version = "0.1.0"
authors = ["Steven Fitzpatrick"]
edition = "2020"
description = "A log collector written in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
